### PR TITLE
Fixes imperative assignment.

### PR DESCRIPTION
**Pull request by linjunpop**

### CODE REVIEW

**Comment by alanpeabody** [comment]
Thank you, but I don't think this is quite right as I believe it could result in nil opts. Also the tests seem to be failing.

Maybe a case statement would be better here?

**Comment by linjunpop** [comment]
You're right, I'll fix this.

**Comment by parndt** [comment]
I believe #124 fixes this

**Comment by alanpeabody** [comment]
Thanks, but #124 got to it first!

**Comment by linjunpop** [comment]
Cool

**Pull request closed without merging**
