### PR TITLE
Update Ecto and Scrivener dependencies to v2

### PR DESCRIPTION
**Pull request by avitex**
- Updated mix dependencies
- `Ecto.Changeset.add_error/4` error in test fixed

### CODE REVIEW

**Comment by alanpeabody** [comment]
@avitex thanks. However I would like to continue to support Ecto 1.0 for a while as well as Ecto 2.0. Do we need the Ecto 2.0 minimum dependency?

At the very minimum lets go for `{:ecto, "~> 1.1 or ~> 2.0"}`

**Comment by avitex** [comment]
Good point, [although Ecto v2 requires at least Elixir v1.2](https://travis-ci.org/AgilionApps/ja_serializer/jobs/139963200#L230).
Would that be suitable?

**Comment by avitex** [comment]
@alanpeabody Good point, I've amended the PR.
Note I also removed the Travid test for Elixir v1.1.1 as [Ecto v2 requires at least v1.2.0](https://travis-ci.org/AgilionApps/ja_serializer/jobs/139963200#L230).

Cheers!

**Comment by alanpeabody** [comment]
Wonderful, thanks. Will put it out at 0.10.1

**Comment by hhff** [comment]
@alanpeabody - can we please get a release @ 0.10.1 ?  I'd love to use scrivener here :)

**Comment by alanpeabody** [comment]
Oh jeeze, thought I had shipped 0.10.1, shipping now!

**Comment by hhff** [comment]
@alanpeabody amazing - thankyou!  working great 👍

**Pull request merged**
