### PR TITLE
per Slack conversation: guard against the use of json vs json-api 

### PR DESCRIPTION
**Pull request by nazarsh**
88 tests, 0 failures

Thanks again for your help in tracking down my resp_header issue!

### CODE REVIEW

**Comment by alanpeabody** [comment]
Going to hold off on merging this for just a bit to see if any 0.10.0 bugs come in.

This will go out as 0.11.0 because it might break things for people.

**Comment by alanpeabody** [comment]
Actually, maybe it would be better to soft deprecate these with a warning instead of just removing them. We also need to update the generators to be correct, as they stand now they are wrong.

Sorry, I know I said removing was what should be done, but I think that will break things for a lot of people.

Thank you for bringing this to my attention, if you want to update this to be a soft deprecate (warning) and update the generators I will happily merge it. If will get something in over the next few days.

**Comment by nazarsh** [comment]
This definitely makes sense - I will see if I can updates done tonight. Thanks for looking into this.

**Comment by nazarsh** [comment]
I hope I didn't miss anything. I've duplicated the tests a bit just to make sure both cases are covered and still return the warnings. Sorry things are not as DRY as they could have been... Happy to make any additional changes though.

**Comment by alanpeabody** [comment]
Looks great, thanks!

**Comment by alanpeabody** [comment]
@nazarsh can you remember why we needed to do this?

**Comment by nazarsh** [comment]
@alanpeabody I think I've triggered an edge case which resulted in incorrect response header (and we talked about not forcing a particular response since people might be wanting to override it)

**Comment by alanpeabody** [comment]
Thanks!

**Pull request merged**
